# -*- coding: utf-8 -*-
"""ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgRgGGKtBfRjl3R--EUvVfJjOsAFqWvM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/financial_regression.csv')
df.describe()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df_cleaned = df.dropna(subset=['gold high', 'gold low'])

X = df_cleaned['gold high']
y = df_cleaned['gold low']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.values.reshape(-1, 1)
X_test = X_test.values.reshape(-1, 1)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

plt.scatter(df['gold high'],df['gold low'],color='purple',marker='*')
plt.title('GRAPH')
plt.xlabel('gold high')
plt.ylabel('gold low')
plt.show()

import joblib
joblib.dump(lr, 'gold high')
import gradio as gr
import joblib
import numpy as np
model = joblib.load('gold high')
def predict_profit(gold_high):
  input_data = np.array([[gold_high]])
  prediction = model.predict(input_data)
  return prediction[0]
iface=gr.Interface(fn=predict_profit,inputs=gr.Number(label='gold high'),outputs='text')
iface.launch()

df = pd.read_csv('/content/youtube_recommendation_dataset -.csv')

df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df.tail()

df_cleaned = df.dropna(subset=['view_count', 'view_count'])

X = df_cleaned[['like_count']]
y = df_cleaned['view_count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.values.reshape(-1, 1)
X_test = X_test.values.reshape(-1, 1)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

plt.scatter(df['view_count'],df['view_count'],color='pink',marker='o')
plt.title('GRAPH')
plt.xlabel('view_count high')
plt.ylabel('view_count low')
plt.show()

import joblib
joblib.dump(lr, 'view_count high')
import gradio as gr
import joblib
import numpy as np
model = joblib.load('view_count high')
def predict_profit(view_count_high):
  input_data = np.array([[view_count_high]])
  prediction = model.predict(input_data)
  return prediction[0]
iface=gr.Interface(fn=predict_profit,inputs=gr.Number(label='view_count high'),outputs='text')
iface.launch()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier

X = df_cleaned[['like_count']]
y = df_cleaned['view_count']

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

plt.plot(df['view_count'],df['view_count'],color='green',marker='o')
plt.xlabel('view_count high')
plt.ylabel('view_count low')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/financial_regression.csv')
df.describe()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier

df_cleaned = df.dropna(subset=['gold high', 'gold low'])

X = df_cleaned['gold high']
y = df_cleaned['gold low']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.values.reshape(-1, 1)
X_test = X_test.values.reshape(-1, 1)

from sklearn.tree import DecisionTreeRegressor
dt1= DecisionTreeRegressor()
dt1.fit(X_train, y_train)

y_pred = dt1.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

from sklearn.tree import plot_tree
plt.figure(figsize=(16,8))
plot_tree(dt1, filled=True, feature_names=['gold high'], rounded=True)
plt.show()

